---
title: "Revert to Sender"
author: "Matthew Wang"
date: "2026-03-26"
output:
  html_document:
    df_print: paged
---

Import data
```{r}
library(tidyverse)
library(zoo)
library(lubridate)

win <- 20
buy_thr <- 0.001
sell_thr <- 2.5

load_data <- function(f){
  read_csv(f) %>%
    mutate(Date = as_datetime(time)) %>%
    arrange(Date) %>%
    select(Date, close) %>%
    rename(Close = close)
}

tickers <- c("AAPL","AMD","NVDA")
data_list <- lapply(tickers, function(t){
  df <- load_data(paste0("data/",t,".csv"))
  df %>%
    mutate(
      MA20 = rollmean(Close, win, fill=NA, align="right"),
      SD20 = rollapply(Close, win, sd, fill=NA, align="right"),
      z = (Close - MA20)/SD20,
      ret = Close/lag(Close) - 1
    )
})
names(data_list) <- tickers
```

Trading signals
```{r}
signal_logic <- function(df){
  df <- df %>% mutate(signal = 0, position = 0)
  pos <- 0
  
  for(i in 2:nrow(df)){
    z_prev <- df$z[i-1]
    
    if(!is.na(z_prev)){
      if(pos==0 && z_prev <= buy_thr) df$signal[i] <- 1
      if(pos==1 && z_prev >= sell_thr) df$signal[i] <- -1
    }
    
    pos <- pos + df$signal[i]
    pos <- max(min(pos,1),0)
    df$position[i] <- pos
  }
  
  df
}

data_list <- lapply(data_list, signal_logic)
```

Strategy Returns
```{r}
compute_returns <- function(df){
  df %>%
    mutate(
      strat_ret = position * ret,
      cum_strat = cumprod(1 + replace_na(strat_ret,0)),
      cum_bh = cumprod(1 + replace_na(ret,0))
    )
}

data_list <- lapply(data_list, compute_returns)
```

Apple trades
```{r}
get_trades <- function(df){
  df %>%
    filter(signal != 0) %>%
    mutate(Type = ifelse(signal==1,"Buy","Sell")) %>%
    select(Date, Type, Price=Close)
}

trades_AAPL <- get_trades(data_list$AAPL)
```

Weekly & monthly stats
```{r}
weekly_stats <- function(df){
  df %>%
    mutate(week = floor_date(Date,"week")) %>%
    group_by(week) %>%
    summarise(
      strat = prod(1+strat_ret, na.rm=TRUE)-1,
      bh = prod(1+ret, na.rm=TRUE)-1
    )
}

monthly_stats <- function(df){
  df %>%
    mutate(month = floor_date(Date,"month")) %>%
    group_by(month) %>%
    summarise(
      strat = prod(1+strat_ret, na.rm=TRUE)-1,
      bh = prod(1+ret, na.rm=TRUE)-1
    )
}

weekly_list <- lapply(data_list, weekly_stats)
monthly_list <- lapply(data_list, monthly_stats)
```

Block means
```{r}
block_means <- function(df, k){
  x <- df$strat_ret
  n <- floor(length(x)/k)
  means <- sapply(1:n, function(i){
    mean(x[((i-1)*k+1):(i*k)], na.rm=TRUE)
  })
  means
}

bm5 <- block_means(data_list$AAPL,5)
bm20 <- block_means(data_list$AAPL,20)
```
Plot 1
```{r}
plot_price_ma <- function(df, ticker){
  ggplot(df, aes(Date, Close)) +
    geom_line() +
    geom_line(aes(y = MA20), color="red") +
    ggtitle(paste("Price + MA20 -", ticker))
}

for(t in tickers){
  g <- plot_price_ma(data_list[[t]], t)
  ggsave(paste0("plots/price_ma20_",t,".pdf"), g, width=7, height=4.5)
}
```

Plot 2
```{r}
plot_z <- function(df, ticker){
  ggplot(df, aes(Date, z)) +
    geom_line() +
    geom_hline(yintercept = buy_thr, color="blue") +
    geom_hline(yintercept = sell_thr, color="red") +
    ggtitle(paste("Z-Score Series -", ticker))
}

for(t in tickers){
  g <- plot_z(data_list[[t]], t)
  ggsave(paste0("plots/zseries_",t,".pdf"), g, width=7, height=4.5)
}
```

Plot 3
```{r}
plot_zdist <- function(df, ticker){
  zvals <- df$z[!is.na(df$z)]
  ggplot(data.frame(z=zvals), aes(z)) +
    geom_histogram(aes(y=..density..), bins=40, fill="gray70") +
    geom_density(color="blue") +
    stat_function(fun = dnorm, args=list(mean=mean(zvals), sd=sd(zvals)), color="red") +
    ggtitle(paste("Z-Score Distribution -", ticker))
}

for(t in tickers){
  g <- plot_zdist(data_list[[t]], t)
  ggsave(paste0("plots/zdist_",t,".pdf"), g, width=7, height=4.5)
}
```

Plot 4
```{r}
plot_zqq <- function(df, ticker){
  zvals <- df$z[!is.na(df$z)]
  ggplot(data.frame(z=zvals), aes(sample=z)) +
    stat_qq() + stat_qq_line() +
    ggtitle(paste("Z-Score QQ Plot -", ticker))
}

for(t in tickers){
  g <- plot_zqq(data_list[[t]], t)
  ggsave(paste0("plots/zqq_",t,".pdf"), g, width=7, height=4.5)
}
```

Cumulative Return Plot
```{r}
plot_cum <- function(df, ticker){
  ggplot(df, aes(Date)) +
    geom_line(aes(y=cum_strat), color="blue") +
    geom_line(aes(y=cum_bh), color="red", linetype="dashed") +
    ggtitle(paste("Cumulative Returns -", ticker))
}

for(t in tickers){
  g <- plot_cum(data_list[[t]], t)
  ggsave(paste0("plots/cum_",t,".pdf"), g, width=7, height=4.5)
}
```

Block Means
```{r}
plot_block_hist <- function(x, k){
  ggplot(data.frame(bm=x), aes(bm)) +
    geom_histogram(bins=30, fill="gray70") +
    ggtitle(paste("Block Means Histogram - k =", k))
}

plot_block_qq <- function(x, k){
  ggplot(data.frame(bm=x), aes(sample=bm)) +
    stat_qq() + stat_qq_line() +
    ggtitle(paste("Block Means QQ - k =", k))
}

ggsave("plots/blockmeans_k5_hist.pdf", plot_block_hist(bm5,5), width=7, height=4.5)
ggsave("plots/blockmeans_k5_qq.pdf", plot_block_qq(bm5,5), width=7, height=4.5)
ggsave("plots/blockmeans_k20_hist.pdf", plot_block_hist(bm20,20), width=7, height=4.5)
ggsave("plots/blockmeans_k20_qq.pdf", plot_block_qq(bm20,20), width=7, height=4.5)
```